import React, {useEffect, useState} from 'react';
import moment from 'moment';
import './App.css';

const Avatar = props => {
  if (props.revealed) {
    return <img src={`http://twivatar.glitch.me/${props.handle}`} />
  } else {
    return <img src="./images/question.png" style={{border: "1px black"}}/>
  }
}


const Tweet = props => {
  const {handle, author, body, likes, datetime, link, revealed} = props.tweet;
  const style = props.style || {};

  return (
    <div className="tweet-outer" style={style}>
      <a href={revealed ? link : "#"}>
        <div className="tweet">
          <div className="tweet-header">
            <div className="tweet-avatar">
              <Avatar {...props.tweet} />
            </div>
            <div className="tweet-screenname-container">
              <div className="tweet-screenname-name">{revealed ? author : "???"} <span className="tweet-verified-screenname"></span></div>
              <div className="tweet-screenname-account">{revealed ? handle : "@???" }</div>
            </div>
            <div className="tweet-brand">
              <div className="tweet-brand-pic" />
            </div>
          </div>
          <div className="tweet-body">
            <p>{body}</p>
            <div className="tweet-info">
              <div className="tweet-heart">
                <div className="tweet-heart-icon"></div>
                <span className="tweet-heart-stat">{revealed ? likes : "???"}</span>
              </div>
              <time className="tweet-time">{revealed ? moment(datetime).format("MMMM Do YYYY, h:mm") : "???"}</time>
              <div className="tweet-info-icon" />
            </div>
          </div>
        </div>
      </a>
    </div>
  )
}


const App = props => {
  let [guessed, setGuessed] = useState(false);

  const tweet = {
    handle: "@paulg",
    author: "Paul Graham",
    body: "What Andy Warhol didn't realize was that the 15 minutes of fame and the 2 minutes hate would converge.",
    likes: 240,
    datetime: "2020-06-17T19:33:46+0000",
    link: "https://twitter.com/paulg/status/1273338063079473154"
  }

  const guess = (human) => {
    setGuessed(true);
  }

  return (
    <div className="wrapper">
      <h1>Twitter Turing Test</h1>
      <p>Can you tell whether this is a real tweet or one generated by a neural network?</p>

      <div className="tweet-container" style={guessed ? {transform: "rotateY(180deg)"} : null}>
        <Tweet tweet={{...tweet, revealed: false}} style={{position: "absolute"}} />
        <Tweet tweet={{...tweet, revealed: true}} style={{position: "absolute", transform: "rotateY(180deg)" }} />

        {/* Add a dummy tweet with hidden visibility so that the elements
            positioned after this match the height of the absolute elements. */}
        <Tweet tweet={tweet} style={{position: "relative", visibility: "hidden"}} />
      </div>

      <div className="answer-container">
        <button className="answer-button" onClick={guess}>
         <div style={{fontSize: "50px"}}>🤖</div>
         <div>Robot</div>
        </button>
        <button className="answer-button" onClick={guess}>
         <div style={{fontSize: "50px"}}>🧠</div>
         <div>Human</div>
        </button>
      </div>

    </div>
  );
}

export default App;
